services:
  marvel-lcg:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: marvel-lcg
    ports:
      - "2345:2345"
    volumes:
      - ./assets:/app/assets
      - ./replays:/app/replays
      - ./runtime:/app/runtime
    command: ["python", "-u", "main.py", "-game_statistics_file", "./runtime/statistics.json", "-game_history_file", "./runtime/statistics.sqlite3", "-campaign_progress_file", "./runtime/save_campaign_progress.json"]
    restart: unless-stopped
